name-template: 'Frontend v$RESOLVED_VERSION'
tag-template: 'frontend-v$RESOLVED_VERSION'
tag-prefix: 'frontend-'

categories:
  - type: 'pre-exclude'
    when:
      paths:
        - pygeoapi/**
        - martin/**
        - public/**
        - dev/**
  - title: '🐛 Bug Fixes'
    semver-increment: patch
    when:
      labels:
        - 'bug'
        - 'fix'
  - title: '🔧 Maintenance'
    semver-increment: patch
    when:
      labels:
        - 'chore'
        - 'dependencies'
        - 'github_actions'
  - title: '🚀 Changes'
    semver-increment: minor

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

template: |
  ## What's Changed
  $CHANGES
