name-template: 'Pygeoapi v$RESOLVED_VERSION'
tag-template: 'pygeoapi-v$RESOLVED_VERSION'
tag-prefix: 'pygeoapi-'

categories:
  - type: 'pre-include'
    when:
      paths:
        - pygeoapi/**
  - title: '🐛 Bug Fixes'
    semver-increment: patch
    when:
      labels:
        - 'bug'
        - 'fix'
  - title: '🔧 Maintenance'
    semver-increment: patch
    when:
      labels:
        - 'chore'
        - 'dependencies'
        - 'github_actions'
  - title: '🚀 Changes'
    semver-increment: minor

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

template: |
  ## What's Changed
  $CHANGES
