name: kartverket-ogc-api

services:
  frontend:
    profiles: [with-frontend]
    build:
      context: ..
    ports:
      - "3000:3000"
    environment:
      - API_BASE_URL=http://pygeoapi:5000
      - DATASET_URL=http://localhost:3000
    depends_on:
      pygeoapi:
        condition: service_healthy
    networks:
      - pygeoapi-network

  pygeoapi:
    build:
      context: ../pygeoapi
    ports:
      - "5001:5000"
    volumes:
      # Mount source files for live editing during development
      - ../pygeoapi/pygeoapi-config.yml:/pygeoapi/local.config.yml
      - ../pygeoapi/processes:/pygeoapi/processes
      - ../pygeoapi/templates:/pygeoapi/custom_templates
      - ../pygeoapi/postgis_mapscript.py:/pygeoapi/postgis_mapscript.py
      - ../pygeoapi/maps.py:/pygeoapi/pygeoapi/api/maps.py
      - ../pygeoapi/mapserver/fonts.txt:/pygeoapi/fonts.txt
      - ../pygeoapi/mapserver/styles:/pygeoapi/styles
      - ../pygeoapi/data:/pygeoapi/data
      - ./volumes/logs:/logs
    environment:
      - PYGEOAPI_URL=http://localhost:5001/
      - db_host=postgis
      - db_name=pygeoapi_test
      - db_user=postgres
      - password=qwer1234
      - CONTAINER_PORT=5000
      - WSGI_WORKERS=1
      - WSGI_WORKER_CLASS=gevent
    restart: always
    depends_on:
      postgis:
        condition: service_healthy
    networks:
      - pygeoapi-network

  t-rex:
    build:
      context: ../trex
    platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwer1234
      - DB_HOST=postgis
      - DB_NAME=pygeoapi_test
      - DATASOURCE_NAME=tellekretser
    depends_on:
      postgis:
        condition: service_healthy
    networks:
      - pygeoapi-network

  postgis:
    build:
      context: ./postgis
    platform: linux/amd64
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - DB_NAME=pygeoapi_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwer1234
    restart: always
    networks:
      - pygeoapi-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  pygeoapi-network:
    driver: bridge

volumes:
  postgres_data:
