import os
import time
import yaml
import fcntl

_MAX_RETRIES = 20
_RETRY_INTERVAL = 1  # seconds

def _wait_for_file(filepath):
    """
    Wait for a file to appear on disk, retrying up to _MAX_RETRIES times.

    Args:
        filepath (str): Path to the file to wait for.

    Returns:
        bool: True if the file exists, False if it was not found after retries.
    """
    for attempt in range(1, _MAX_RETRIES + 1):
        if os.path.exists(filepath):
            return True
        print(
            f"OpenAPI spec not found at {filepath} "
            f"(attempt {attempt}/{_MAX_RETRIES}). "
            f"Retrying in {_RETRY_INTERVAL}s..."
        )
        time.sleep(_RETRY_INTERVAL)
    return False

def remove_post_endpoints(pattern):
    """
    Remove POST endpoints from the OpenAPI spec file if they match the given pattern.

    Waits for the file to appear on disk (it is generated by pygeoapi on startup)
    before attempting modification.

    Args:
        pattern (re.Pattern): Compiled regex pattern to match paths against.
    """
    openapi_file = os.environ.get('PYGEOAPI_OPENAPI')
    if not openapi_file:
        print("PYGEOAPI_OPENAPI environment variable is not set. Skipping POST endpoint removal.")
        return

    if not _wait_for_file(openapi_file):
        print(
            f"WARNING: OpenAPI spec file not found at {openapi_file} after "
            f"{_MAX_RETRIES * _RETRY_INTERVAL}s. POST endpoints will NOT be "
            f"removed from the spec. This may happen on a fresh deployment if "
            f"pygeoapi has not yet generated the file."
        )
        return

    print(f"Modifying OpenAPI spec at {openapi_file} to remove POST endpoints matching pattern")
    try:
        with open(openapi_file, 'r+') as _f:
            # Acquire an exclusive lock to prevent race conditions properly
            fcntl.flock(_f, fcntl.LOCK_EX)
            try:
                _spec = yaml.safe_load(_f)

                if isinstance(_spec, dict):
                    paths = _spec.get('paths', {})
                    paths_to_modify = [
                        p for p in paths
                        if pattern.search(p) and 'post' in paths[p]
                    ]

                    for p in paths_to_modify:
                        paths[p].pop('post')

                    if paths_to_modify:
                        # Move pointer to beginning of file and truncate it
                        _f.seek(0)
                        _f.truncate()
                        yaml.safe_dump(_spec, _f, allow_unicode=True, sort_keys=False)
                elif _spec is not None:
                    print(f"OpenAPI spec at {openapi_file} is not a valid dictionary. Skipping modification.")
            finally:
                # Release the lock
                fcntl.flock(_f, fcntl.LOCK_UN)
    except yaml.YAMLError as exc:
        print(f"Failed to parse OpenAPI spec at {openapi_file}: {exc}")
    except Exception as e:
        print(f"Failed to modify OpenAPI spec at {openapi_file}: {e}")
