upstream backend {
    server pygeoapi:5000;
}

upstream frontend {
    server front-end:3000;
}

# Trust Istio and local proxies
set_real_ip_from 127.0.0.1;   # Localhost (used by sidecars)
set_real_ip_from 127.0.0.6;   # Istio specfic
set_real_ip_from 10.0.0.0/8;  # Internal network (adjust as needed)

# Extract the real client IP from X-Forwarded-For
real_ip_header X-Forwarded-For;

# If X-Forwarded-For contains multiple IPs, recursively resolve to the first non-trusted IP
real_ip_recursive on;

# Variables for routing
map $arg_f $is_json_param {
    default         0;
    json            1;
    pbf             1;
}

map $http_accept $is_json_accept {
    default         0;
    "~*application/json" 1;
}

map "$is_json_param:$is_json_accept" $target_upstream {
    "1:0"           backend;
    "0:1"           backend;
    "1:1"           backend;
    default         frontend;
}

server {
  listen 80;
#   listen 443 ssl;
  server_name _;

#   ssl_certificate /etc/ssl/certs/selfsigned.crt;
#   ssl_certificate_key /etc/ssl/private/selfsigned.key;

  # Tune this as you see fit
  proxy_connect_timeout 60s;
  proxy_send_timeout 60s;
  proxy_read_timeout 60s;
  send_timeout 60s;

    location /openapi {
        proxy_pass http://backend;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Accept $http_accept;

        proxy_connect_timeout 5s;
        proxy_read_timeout 30s;
    }

    location / {
        proxy_pass http://$target_upstream;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Accept $http_accept;

        proxy_connect_timeout 5s;
        proxy_read_timeout 30s;
    }
}
