server:
  bind:
    host: 0.0.0.0
    port: 5000
  cors: true
  url: ${PYGEOAPI_URL}
  mimetype: application/json; charset=UTF-8
  encoding: utf-8
  gzip: false
  languages:
    - nb-NO
    - en-US
  pretty_print: true
  limits:
    default_items: 20
    max_items: 1000
  map:
    url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
    attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
  admin: false
  templates:
    path: /pygeoapi/custom_templates
    static: /pygeoapi/pygeoapi/static

logging:
  level: INFO

metadata:
  identification:
    title:
      nb-NO: Administrative enheter
      en-US: Administrative units
    description:
      nb-NO: >
        Dette er en referanseimplementasjon beregnet for utviklere som evaluerer eller tester OGC API-frontend-applikasjonen.
        Den skal ikke brukes som en produksjonstjeneste eller som en autoritativ datakilde.
        Datasettene som er inkludert (administrative grenser for Norge og eksempel raster data) er kun levert for demonstrasjons- og testformål.
      en-US: >
        This is a reference implementation intended for developers evaluating or testing the OGC API frontend application.
        It should not be used as a production service or as an authoritative source of data.
        The datasets included (administrative boundaries for Norway and example raster data) are provided solely for demonstration and testing purposes.
    keywords:
      nb-NO:
        - Fylke
        - Kommune
        - Administrativ inndeling
        - Administrative grenser
        - Fylkesgrenser
        - Kommunegrenser
        - Riksgrense
        - Tellekretser
      en-US:
        - County
        - Municipality
        - Administrative division
        - Administrative boundaries
        - County boundaries
        - Municipal boundaries
        - National border
        - Counting districts
    keywords_type: theme
    terms_of_service: https://www.kartverket.no/geodataarbeid/norge-digitalt/partsinformasjon/avtaler-og-vilkar/norge-digitalt-lisens
    url: https://www.kartverket.no

  license:
    name: Norge digitalt-lisens
    url: https://www.kartverket.no/geodataarbeid/norge-digitalt/partsinformasjon/avtaler-og-vilkar/norge-digitalt-lisens
  provider:
    name: Kartverket
    url: https://www.kartverket.no
  contact:
    name: Kartverket
    email: post@kartverket.no
    url: https://www.kartverket.no

resources:
  get-distinct-values:
    type: process
    processor:
      name: distinct_values.DistinctValuesProcessor
  export-collection-gpkg:
    type: process
    processor:
      name: processes.gpkg_collection.ExportCollectionGpkgProcessor
  export-all-gpkg:
    type: process
    processor:
      name: processes.gpkg_all_collections.ExportAllGpkgProcessor
  export-by-area-gpkg:
    type: process
    processor:
      name: processes.gpkg_by_area.ExportByAreaGpkgProcessor
  export-collection-csv:
    type: process
    processor:
      name: processes.csv_collection.ExportCollectionCsvProcessor

  fylker:
    type: collection
    title:
      nb-NO: Fylker
      en-US: Counties
    description:
      nb-NO: >
        Datasettet viser fylkesinndelingen i landet med de mest nøyaktige grensene som er registrert digitalt og som er samlet i ett datasett
      en-US: >
        The dataset shows the county division of the country with the most accurate boundaries registered digitally and compiled in one dataset.
    keywords:
      nb-NO:
        - Fylke
        - Fylkesgrense
      en-US:
        - County
        - County boundary
    extents:
      spatial:
        bbox: [4.087524, 57.759005, 31.761592, 71.384878]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    links:
      - type: text/html
        rel: related
        title: Geonorge link
        href: https://kartkatalog.geonorge.no/metadata/administrative-enheter-fylker/6093c8a8-fa80-11e6-bc64-92361f002671
      - type: image/png
        rel: preview
        title:
          nb-NO: Forhåndsvisning
          en-US: Preview
        href: /assets/collection-images/fylker.png
    providers:
      - type: feature
        name: PostgreSQL
        data:
          host: ${db_host}
          dbname: ${db_name}
          user: ${db_user}
          password: ${password}
          search_path: [public]
        id_field: nr
        properties:
          - navn
          - nr
        table: fylker
        geom_field: geometry
        crs:
          - http://www.opengis.net/def/crs/OGC/1.3/CRS84
          - http://www.opengis.net/def/crs/EPSG/0/25832
          - http://www.opengis.net/def/crs/EPSG/0/25833
          - http://www.opengis.net/def/crs/EPSG/0/25835
          - http://www.opengis.net/def/crs/EPSG/0/4258
          - http://www.opengis.net/def/crs/EPSG/0/4326
          - http://www.opengis.net/def/crs/EPSG/0/3857
        storage_crs: http://www.opengis.net/def/crs/EPSG/0/25833

      - type: tile
        name: MVT-postgresql
        data:
          host: ${db_host}
          dbname: ${db_name}
          user: ${db_user}
          password: ${password}
          search_path: [public]
        id_field: nr
        table: fylker
        geom_field: geometry
        storage_crs: http://www.opengis.net/def/crs/EPSG/0/25833
        options:
          zoom:
            min: 0
            max: 18
        format:
          name: pbf
          mimetype: application/vnd.mapbox-vector-tile

      - type: map
        name: MapScript
        data: PG:host='${db_host}' dbname='${db_name}' user='${db_user}' password='${password}' port=5432 tables=public.fylker
        options:
          type: MS_LAYER_POLYGON
          layer: fylker
          projection: 25833
          style: /pygeoapi/styles/fylker.inc
        format:
          name: png
          mimetype: image/png


  kommuner:
    type: collection
    title:
      nb-NO: Kommuner
      en-US: Municipalities
    description:
      nb-NO: >
        Datasettet viser kommuneinndelingen i landet med de mest nøyaktige grensene som er registrert digitalt og som er samlet i ett datasett.
      en-US: >
        The dataset shows the municipality division of the country with the most accurate boundaries registered digitally and compiled in one dataset.
    download:
      area_filters:
        - type: fylke
          collection: fylker
          name_field: navn
          label: Fylke
    keywords:
      nb-NO:
        - Kommune
        - Kommunegrenser
      en-US:
        - Municipality
        - Municipal boundaries
    extents:
      spatial:
        bbox: [4.087524, 57.759005, 31.761592, 71.384878]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    links:
      - type: text/html
        rel: related
        title: Geonorge link
        href: https://kartkatalog.geonorge.no/metadata/administrative-enheter-kommuner/041f1e6e-bdbc-4091-b48f-8a5990f3cc5b
      - type: image/png
        rel: preview
        title:
          nb-NO: Forhåndsvisning
          en-US: Preview
        href: /assets/collection-images/kommuner.png
    providers:
      - type: feature
        name: PostgreSQL
        data:
          host: ${db_host}
          dbname: ${db_name}
          user: ${db_user}
          password: ${password}
          search_path: [public]
        id_field: nr
        properties:
          - navn
          - nr
        title_field: navn
        table: kommuner
        geom_field: geometry
        crs:
          - http://www.opengis.net/def/crs/OGC/1.3/CRS84
          - http://www.opengis.net/def/crs/EPSG/0/25832
          - http://www.opengis.net/def/crs/EPSG/0/25833
          - http://www.opengis.net/def/crs/EPSG/0/25835
          - http://www.opengis.net/def/crs/EPSG/0/4258
          - http://www.opengis.net/def/crs/EPSG/0/4326
          - http://www.opengis.net/def/crs/EPSG/0/3857
        storage_crs: http://www.opengis.net/def/crs/EPSG/0/25833
      - type: tile
        name: MVT-postgresql
        data:
          host: ${db_host}
          dbname: ${db_name}
          user: ${db_user}
          password: ${password}
          search_path: [public]
        id_field: nr
        table: kommuner
        geom_field: geometry
        storage_crs: http://www.opengis.net/def/crs/EPSG/0/25833
        options:
          zoom:
            min: 0
            max: 18
        format:
          name: pbf
          mimetype: application/vnd.mapbox-vector-tile
      - type: map
        name: MapScript
        data: PG:host='${db_host}' dbname='${db_name}' user='${db_user}' password='${password}' port=5432 tables=public.kommuner
        options:
          type: MS_LAYER_POLYGON
          layer: kommuner
          projection: 25833
          style: /pygeoapi/styles/kommuner.inc
        format:
          name: png
          mimetype: image/png


  tellekretser:
    type: collection
    title:
      nb-NO: Tellekretser
      en-US: Counting districts
    description:
      nb-NO: >
        Datasettet viser tellekretser i Norge
      en-US: >
        The dataset shows counting districts in Norway.
    download:
      area_filters:
        - type: fylke
          collection: fylker
          name_field: navn
          label: Fylke
        - type: kommune
          collection: kommuner
          name_field: navn
          label: Kommune
    keywords:
      nb-NO:
        - Tellekrets
        - Statistikk
      en-US:
        - Counting district
        - Statistics
    extents:
      spatial:
        bbox: [4.626095, 57.977101, 31.125157, 71.188325]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    links:
      - type: image/png
        rel: preview
        title:
          nb-NO: Forhåndsvisning
          en-US: Preview
        href: /assets/collection-images/tellekretser.png
    providers:
      - type: feature
        name: schema_provider.SchemaPostgreSQLProvider
        schema_file: /pygeoapi/schemas/tellekrets.json
        data:
          host: ${db_host}
          dbname: ${db_name}
          user: ${db_user}
          password: ${password}
          search_path: [public]
        id_field: id
        properties:
          - navn
          - nr
          - fylkesnummer
          - kommunenummer
          - valgdistriktsnummer_valgdirektoratet
          - valgdistriktsnummer_ssb
        table: tellekrets
        geom_field: geometry
        crs:
          - http://www.opengis.net/def/crs/OGC/1.3/CRS84
          - http://www.opengis.net/def/crs/EPSG/0/25832
          - http://www.opengis.net/def/crs/EPSG/0/25833
          - http://www.opengis.net/def/crs/EPSG/0/25835
          - http://www.opengis.net/def/crs/EPSG/0/4258
          - http://www.opengis.net/def/crs/EPSG/0/4326
          - http://www.opengis.net/def/crs/EPSG/0/3857
        storage_crs: http://www.opengis.net/def/crs/EPSG/0/25833
      - type: tile
        name: MVT-proxy
        data: http://bbox-tile-server:8080/xyz/tellekretser/{z}/{x}/{y}.mvt
        options:
          zoom:
            min: 0
            max: 15
          schemes:
            - WebMercatorQuad
        format:
          name: pbf
          mimetype: application/x-protobuf; type=mapbox-vector-tile

  tellekretser_polar:
    type: collection
    title:
      nb-NO: Tellekretser i polar projeksjonen - test for tiles
      en-US: Counting districts in polar projection - tile test
    description:
      nb-NO: >
        Datasettet viser tellekretser i Norge
      en-US: >
        The dataset shows counting districts in Norway.
    keywords:
      nb-NO:
        - Tellekrets
        - Statistikk
      en-US:
        - Counting district
        - Statistics
    extents:
      spatial:
        bbox: [4.626095, 57.977101, 31.125157, 71.188325]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: feature
        name: schema_provider.SchemaPostgreSQLProvider
        schema_file: /pygeoapi/schemas/tellekrets.json
        data:
          host: ${db_host}
          dbname: ${db_name}
          user: ${db_user}
          password: ${password}
          search_path: [public]
        id_field: id
        properties:
          - navn
          - nr
          - fylkesnummer
          - kommunenummer
          - valgdistriktsnummer_valgdirektoratet
          - valgdistriktsnummer_ssb
        table: tellekrets
        geom_field: geometry
        crs:
          - http://www.opengis.net/def/crs/OGC/1.3/CRS84
          - http://www.opengis.net/def/crs/EPSG/0/25832
          - http://www.opengis.net/def/crs/EPSG/0/25833
          - http://www.opengis.net/def/crs/EPSG/0/25835
          - http://www.opengis.net/def/crs/EPSG/0/4258
          - http://www.opengis.net/def/crs/EPSG/0/4326
          - http://www.opengis.net/def/crs/EPSG/0/3857
        storage_crs: http://www.opengis.net/def/crs/EPSG/0/25833

      - type: tile
        name: MVT-proxy
        data: http://bbox-tile-server:8080/xyz/tellekrets_polar/{z}/{x}/{y}.mvt
        options:
          zoom:
            min: 0
            max: 12
          schemes:
            - EPSG3575Quad
        format:
          name: pbf
          mimetype: application/x-protobuf; type=mapbox-vector-tile



  norge-raster:
    type: collection
    title:
      nb-NO: Norge raster
      en-US: Norway raster
    description:
      nb-NO: Topografi-batymetri-dekning (EGM2008-høyde)
      en-US: Topography-Bathymetry coverage (EGM2008 height)
    keywords:
      nb-NO:
        - dekning
        - raster
        - topografi
        - batymetri
      en-US:
        - coverage
        - raster
        - topography
        - bathymetry
    extents:
      spatial:
        bbox: [3.0, 56.5, 32.0, 71.5]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    links:
      - type: text/html
        rel: related
        title: NCEI/NOAA
        href: https://www.ncei.noaa.gov/
      - type: image/png
        rel: preview
        title:
          nb-NO: Forhåndsvisning
          en-US: Preview
        href: /assets/collection-images/norge-raster.png
    providers:
      - type: coverage
        name: rasterio
        data: ${NORGE_EXAMPLE_RASTER_PATH}
        format:
          name: GTiff
          mimetype: image/tiff; application=geotiff
      - type: map
        name: MapScript
        data: ${NORGE_EXAMPLE_RASTER_PATH}
        options:
          type: MS_LAYER_RASTER
        format:
          name: png
          mimetype: image/png
        storage_crs: http://www.opengis.net/def/crs/EPSG/0/4326


