name: Release Drafter

on:
  push:
    branches: [main]

jobs:
  draft-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: release-drafter/release-drafter@v7
        with:
          config-name: release-drafter-frontend.yml

  draft-pygeoapi:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: release-drafter/release-drafter@v7
        with:
          config-name: release-drafter-pygeoapi.yml
